### ISSUE TITLE
Image upload doesn't work 

### ISSUE THREAD

**Issue by csandanov** [wodby/wordpress#1]
Caused by imagemagick https://github.com/alpinelinux/aports/pull/5402

**Comment by Rozkalns** [comment]
@csandanov is that this issue?

<img width="1232" alt="screenshot 2018-11-07 at 05 59 46" src="https://user-images.githubusercontent.com/8157701/48109982-6be27900-e252-11e8-94fd-e3089dd1974b.png">

**Comment by csandanov** [comment]
Yep, should work with 4.8.x stability tags though

**Comment by Rozkalns** [comment]
Thanks! Did you mean, Wordpress's 4.8.x ?

In this particular example I have wodby/wordpress:4-7.2-4.9.1 image used.

Have you tried out graphicsmagick instead of imagemagick on wodby/php image? Got some conclusions?

**Comment by csandanov** [comment]
> I have wodby/wordpress:4-7.2-4.9.1 image used.

here's your stability tag is 4.9.1, see README explaining stability tags

there's still no stable release of gmagick pecl extension and I'm not sure whether WP core supports gmagick out of the box, besides imagemagick issues come from openmp on musl, gmagick is no different in that regard

**Comment by Rozkalns** [comment]
> Yep, should work with 4.8.x stability tags though

Thanks, finally understood :) Took release 4.8.5 from the list found here https://github.com/wodby/wordpress/releases and it works. 

Ping here when when fixed on 4.9.x

**Comment by csandanov** [comment]
Fixed in 4.9.4
